apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: alloy-sa
  namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    // 1. OTEL RECEIVER (This answers your doubt!)
    otelcol.receiver.otlp "default" {
      grpc { endpoint = "0.0.0.0:4317" }
      http { endpoint = "0.0.0.0:4318" }
      output {
        metrics = [otelcol.exporter.prometheus.cloud.input]
      }
    }

    otelcol.exporter.prometheus.cloud {
      forward_to = [prometheus.remote_write.grafana_cloud.receiver]
    }

    // 2. METRIC SCRAPING
    prometheus.exporter.unix "local" { }
    prometheus.scrape "unix_metrics" {
      targets    = prometheus.exporter.unix.local.targets
      forward_to = [prometheus.remote_write.grafana_cloud.receiver]
    }

    // 3. REMOTE WRITE
    prometheus.remote_write "grafana_cloud" {
      endpoint {
        url = "https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push"
        basic_auth {
          username = env("GRAFANA_USER")
          password = env("GRAFANA_TOKEN")
        }
      }
      external_labels = { cluster = "eagle-eye" }
    }
---
apiVersion: apps/v1
kind: DaemonSet # Changed from Deployment for better coverage
metadata:
  name: grafana-alloy
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      serviceAccountName: alloy-sa
      containers:
      - name: alloy
        image: grafana/alloy:latest
        args: ["run", "/etc/alloy/config.alloy", "--storage.path=/var/lib/alloy/data"]
        env:
          - name: GRAFANA_USER
            valueFrom: { secretKeyRef: { name: grafana-cloud-credentials, key: user } }
          - name: GRAFANA_TOKEN
            valueFrom: { secretKeyRef: { name: grafana-cloud-credentials, key: key } }
        volumeMounts:
          - name: config
            mountPath: /etc/alloy
      volumes:
        - name: config
          configMap: { name: alloy-config }