apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: alloy-sa
  namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    // 1. COLLECT HOST METRICS (CPU/RAM of the Hardware)
    prometheus.exporter.unix "local" { }

    prometheus.scrape "unix_metrics" {
      targets    = prometheus.exporter.unix.local.targets
      forward_to = [prometheus.remote_write.grafana_cloud.receiver]
    }

    // 2. COLLECT CONTAINER METRICS (Fixes Query 3 and 4)
    // This talks to the Kubelet on port 10250 to get pod stats
    prometheus.scrape "kubernetes_nodes_cadvisor" {
      targets = [{
        __address__ = "localhost:10250",
      }]
      scheme = "https"
      authorization {
        type = "Bearer"
        credentials_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      }
      tls_config {
        insecure_skip_verify = true
      }
      forward_to = [prometheus.remote_write.grafana_cloud.receiver]
    }

    // 3. SEND EVERYTHING TO GRAFANA CLOUD
    prometheus.remote_write "grafana_cloud" {
      endpoint {
        url = "https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push"
        basic_auth {
          username = env("GRAFANA_USER")
          password = env("GRAFANA_TOKEN")
        }
      }
      external_labels = {
        cluster = "eagle-eye",
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      serviceAccountName: alloy-sa
      hostNetwork: true  // Required to talk to localhost:10250 directly
      containers:
      - name: alloy
        image: grafana/alloy:latest
        args: ["run", "/etc/alloy/config.alloy", "--storage.path=/var/lib/alloy/data"]
        env:
          - name: GRAFANA_USER
            valueFrom: { secretKeyRef: { name: grafana-cloud-credentials, key: user } }
          - name: GRAFANA_TOKEN
            valueFrom: { secretKeyRef: { name: grafana-cloud-credentials, key: key } }
        volumeMounts:
          - name: config
            mountPath: /etc/alloy
      volumes:
        - name: config
          configMap: { name: alloy-config }